import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//
import { useSelector, useDispatch } from 'react-redux'

import Increment from '../components/Increment'
import Decrement from '../components/Decrement'

export default function Home() {
    const count = useSelector((state) => state.counter.value)

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <div>
                <span>{count}</span>
                <Increment />
                <Decrement />
            </div>
        </div>
    )
}
